- name: Check if otrs is already installed
  stat:
    path: "{{ otrs_install_path }}/Kernel"
  register: otrs_kernel_stat

- name: check if otrs installation archive exists
  local_action: "stat path={{otrs_tar_file}}"
  register: otrs_tar_file_stat

- fail:
    msg: "otrs installation archive not found"
  when: not otrs_kernel_stat.stat.exists and not otrs_tar_file_stat.stat.exists and install_mode == "install"

- name: Prepare
  include_tasks:
    file: prepare.yml
  when: install_mode == "configure" or install_mode == "prepare" or install_mode == "install"

- name: Install
  include_tasks:
    file: install.yml
  when: install_mode == "install"

- name: Configure
  include_tasks:
    file: configure.yml
  when: install_mode == "configure" or install_mode == "install"